import { EditorialStudy } from '../schema';

export const john1PrologueStudy: EditorialStudy = {
  schemaVersion: 1,
  id: 'john-1-1-18-before-bethlehem',
  version: '0.1.0-draft',
  locale: 'pt-BR',
  reference: {
    editionId: 'blivre-2018.2.0-tr',
    bookCode: 'JHN',
    chapter: 1,
    startVerse: 1,
    endVerse: 18,
  },
  title: 'O Deus que veio morar entre nós',
  lead: 'João não começa com uma manjedoura. Ele abre uma porta muito mais antiga: “No princípio”. Antes de acompanhar Jesus pelas estradas da Galileia, o evangelho quer que saibamos quem está caminhando por elas.',
  sources: [
    {
      id: 'blivre-john-1',
      kind: 'scripture',
      title: 'Bíblia Livre — João 1:1–18',
      edition: 'release 2018.2.0 / Textus Receptus',
      locator: 'João 1:1–18',
      license: 'CC BY 3.0 Brasil (corpus integrado)',
    },
    {
      id: 'blivre-genesis-1',
      kind: 'scripture',
      title: 'Bíblia Livre — Gênesis 1',
      edition: 'release 2018.2.0 / Textus Receptus',
      locator: 'Gênesis 1:1–5',
      license: 'CC BY 3.0 Brasil (corpus integrado)',
    },
  ],
  claims: [
    {
      id: 'john-prologue-preexistence',
      layer: 'interpretation',
      text: 'O prólogo apresenta a Palavra como existente no princípio, junto de Deus e identificada como Deus, antes de dizer que ela se fez carne.',
      sourceIds: ['blivre-john-1'],
      certainty: 'high',
    },
    {
      id: 'john-genesis-opening',
      layer: 'context',
      text: 'A expressão de abertura “No princípio” cria uma conexão literária visível com a abertura de Gênesis, acompanhada em João por criação, vida e luz.',
      sourceIds: ['blivre-john-1', 'blivre-genesis-1'],
      certainty: 'high',
    },
    {
      id: 'john-baptist-witness',
      layer: 'interpretation',
      text: 'João Batista é apresentado como testemunha da Luz e explicitamente distinguido da própria Luz.',
      sourceIds: ['blivre-john-1'],
      certainty: 'high',
    },
    {
      id: 'son-reveals-father',
      layer: 'application',
      text: 'A aplicação cristã do trecho parte de sua afirmação final de que o Filho torna Deus conhecido: conhecer Jesus é central para conhecer como Deus se revelou.',
      sourceIds: ['blivre-john-1'],
      certainty: 'high',
    },
  ],
  sections: [
    {
      id: 'central',
      eyebrow: 'DESCOBERTA CENTRAL',
      title: 'João começa antes de Belém',
      body: 'O prólogo não apresenta Jesus apenas como alguém que entrou na história. João recua ao “princípio” e descreve a Palavra já junto de Deus — e, ao mesmo tempo, como Deus. A cena de Belém só pode ser entendida depois dessa afirmação maior: aquele que se fez carne não começou a existir quando nasceu.',
      layer: 'interpretation',
      claimIds: ['john-prologue-preexistence'],
    },
    {
      id: 'context',
      eyebrow: 'CONTEXTO',
      title: '“No princípio” acende uma memória',
      body: 'A abertura ecoa Gênesis por linguagem diretamente observável no texto. Isso não transforma cada palavra em código secreto; cria um horizonte literário. João apresenta a chegada de Jesus dentro da linguagem de criação, vida e luz.',
      layer: 'context',
      claimIds: ['john-genesis-opening'],
    },
    {
      id: 'interpretation',
      eyebrow: 'INTERPRETAÇÃO',
      title: 'A Palavra não é João Batista',
      body: 'O texto interrompe o prólogo para apresentar “um homem enviado por Deus, cujo nome era João”. Em seguida, esclarece: ele não era a Luz. A distinção impede fundir o testemunho com aquele de quem ele testemunha.',
      layer: 'interpretation',
      claimIds: ['john-baptist-witness'],
    },
    {
      id: 'application',
      eyebrow: 'APLICAÇÃO',
      title: 'Conhecer Deus ganha um rosto',
      body: 'O movimento final do trecho é revelação: o Filho torna o Pai conhecido. A aplicação nasce do argumento do texto — a fé cristã não busca um Deus abstrato atrás de Jesus; olha para Jesus para compreender quem Deus se revelou ser.',
      layer: 'application',
      claimIds: ['son-reveals-father'],
    },
  ],
  review: {
    status: 'draft',
    reviewer: null,
    reviewedAt: null,
  },
};
